site:
  title: OCS Standard Operating Procedures 
  url: https://mid998.github.io/ocs-sop
  start_page: sop::index.adoc
  robots: allow
  keys:
    google_analytics: 'G-PDMKGVZNGE'
content:
  sources:
  - url: https://github.com/mid998/ocs-sop.git
    #- url: .
    branches: [HEAD]
    start_paths: [sop]
    edit_url: '{web_url}/edit/{refname}/{path}'

ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ui
# output:
  # clean: true
  # dir: ./site
  #

asciidoc:
  attributes:
    bad-pod: ${MYPOD}
    title_message: "Message"
    title_description: "Description"
    title_severity: "Severity"
    title_procedure: "Procedure for Resolution"
    title_logs: "Gathering Logs"
  extensions:
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
